version: '3'

services:
  # database
  postgres:
    container_name: postgis-db
    image: mdillon/postgis:10
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/postgres:/var/lib/postgresql/data # banco de dados
      - ./db/data:/mnt/disks/data # tabelas e bancos de backup
  # admin of database
  pgadmin:
    container_name: db-pgadmin
    image: thajeztah/pgadmin4
    ports:
      - '5050:5050'
    volumes:
      - ./pgadmin:/pgadmin
    depends_on:
      - postgres
  # backend
  backend:
    container_name: django-backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  # project frontend
  frontend:
    container_name: vue-frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/home/frontend
    command: "npm run serve"